### ISSUE TITLE
wrong name in mod.conf

### ISSUE THREAD

**Issue by VanessaE** [Lejo1/vps_blocker#1]
In your mod.conf, you have `name = VPS Blocker`, but this is incorrect, it needs to be the technical name of the mod.  When run as-is, this throws the following error:
```
2019-06-30 04:36:11: ERROR[Main]: ModError: Error loading mod "VPS Blocker": Mod name does not follow naming conventions: Only characters [a-z0-9_] are allowed.
```

Change it to `name = vps_blocker` and it works.  This is probably the correct setting.

Secondary, the mod should actually be named VP**N** blocker, to refer to the service, and not VPS, as that's just the underlying server on the cloud running the VPN software.

**Comment by Lejo1** [comment]
Ah ok thanks I will change this
I thought it should be the name which gets shown
It’s called VPS blocker as it blocks any hosted servers

**Comment by VanessaE** [comment]
Well, a VPS is merely the term to describe the guest OS inside virtual machine like VMware or VirtualBox, when placed online and made accessible to the world at large, to some degree, and is often used to host cheap, low-end Minetest game instances (think Linode or AWS).

A VPN is just a proxy/anonymizing service, and may not necessarily be running on a VPS (for example, technically my ZNC instance could qualify as that, and it runs on a dedicated server along with my other online stuff).

**Comment by Lejo1** [comment]
I agree VPS means something different.
I will think about to change this, but VPN is too less it doesn't include Proxys, ...
People just understand under VPS VPN+Proxys+Hostings
