### ISSUE TITLE
Not blocking some IPs

### ISSUE THREAD

**Issue by VanessaE** [Lejo1/vps_blocker#3]
A player (actually a bot) got on one of my servers, from an IP that should have been blocked.  The mod seems to be reaching out to iphub like it's supposed to (the site shows a dozen hits in the past hour, and a few hundred for the day so far), and they have a listing for the offending IP:

```
$ curl http://v2.api.iphub.info/ip/159.203.184.186 -H "X-Key: [redacted]"
{"ip":"159.203.184.186","countryCode":"US","countryName":"United States","asn":14061,"isp":"DIGITALOCEAN-ASN","block":1,"hostname":"159.203.184.186"}
```

The offending player account was quickly banned by one of my admins, but not before the bot was able to spend some time on the server; we believe it was trying to steal a copy of the server's map.

I asked someone to double-check for me, just so I could get a log result.  He was using another large VPN, which iphub also has a listing for.  Same issue - he was not blocked.  In Minetest's log:

```
2020-04-08 20:52:09: ACTION[Server]: minetestNoob2018 [::ffff:144.202.40.156] joins game.
2020-04-08 20:52:09: ACTION[Server]: minetestNoob2018 joins game. List of players: [etc etc]
```

Could that leading `::ffff:` be interfering?  This is an IPv6-enabled system.  It seems if you get an IPv4 address (i.e. there's a "." in the address somewhere), and this string is at the start, then you should just strip it off before sending the IP request to the blacklist server.

Anyway this mod needs to log both successes and failures in IP lookups.

**Comment by Lejo1** [comment]
> Could that leading ::ffff: be interfering?

That's the only reason I exspect. Iphub.info tells me that is a private address so it's listed wrong.
Wrote that to Iphub to prevent others from searching for the reason for that.

The mod is only tested for IPv4 but should work for IPv6 as well.

> Anyway this mod needs to log both successes and failures in IP lookups.

Didn't needed this yet as actions are reported by mod security:
`2020-04-09 00:00:24: ACTION[Server]: Mod performs HTTP request with URL http://v2.api.iphub.info/ip/...`
If you see the fail below this you know it failed.

**Comment by VanessaE** [comment]
> That's the only reason I exspect.

So fix it :wink: 

> Iphub.info tells me that is a private address so it's listed wrong.
> Wrote that to Iphub to prevent others from searching for the reason for that.

Regarding 144.202.40.156 , the person who did the test DID say he was having some problems with proxying Minetest like this, so it could be bogus, but the one from the bot that resolves to Digital Ocean definitely should have been blocked. :smile:

> Didn't needed this yet as actions are reported by mod security:

That message did not appear in my log because while I have mod security enabled, I have `vps_blocker` listed as a trusted mod, so mod security will not interfere with it and that message wouldn't appear anyway.  Or I think it works like that?

Anyway, by logging I mean i.e. after the mod has done a successful look-up of an IP, it should report whether it ought be blocked or not.

**Comment by Lejo1** [comment]
> So fix it 😉

Iphub now filters these prefix out :)
> but the one from the bot that resolves to Digital Ocean definitely should have been blocked. 

I have no idea why he didn't got blocked :(

> That message did not appear in my log because while I have mod security enabled, I have vps_blocker listed as a trusted mod, so mod security will not interfere with it and that message wouldn't appear anyway. Or I think it works like that?

Stange, it seems to be [infostream](https://github.com/minetest/minetest/blob/master/src/script/lua_api/l_http.cpp#L94) but I anyway get a message in action stream
> Anyway, by logging I mean i.e. after the mod has done a successful look-up of an IP, it should report whether it ought be blocked or not.

Will add that!

**Comment by Lejo1** [comment]
dd9ec8ea3e880b700985fd199fde698fa07a0c71
Done!

**Comment by VanessaE** [comment]
I see the logging, but not any changes that strip out the prefix?

**Comment by Lejo1** [comment]
> I see the logging, but not any changes that strip out the prefix?

Yep, Iphub strips them now out.

**Comment by VanessaE** [comment]
AH! okay :smile:
