### ISSUE TITLE
Nastyhosts replacement

### ISSUE THREAD

**Issue by Lejo1** [Lejo1/vps_blocker#5]
As nastyhosts is not working anymore an alternative is needed.

Should be working and no registration needed.

**Comment by FriendlyGamer** [comment]
> As nastyhosts is not working anymore an alternative is needed.
> 
> Should be working and no registration needed.

I think in the meantime the mod should requires the API code or else it will not work. So people are not running A) Falsified feelings their servers are "secured" and/or B) Running code that is failing as the result of this service not existing.

**Comment by Lejo1** [comment]
> I think in the meantime the mod should requires the API code or else it will not work. So people are not running A) Falsified feelings their servers are "secured" and/or B) Running code that is failing as the result of this service not existing.

Yeah I will, I just hoped nastyhosts will get online again :/

**Comment by Lejo1** [comment]
I added proxycheck.io and removed nastyhosts

Anyway I might add more services.
